---
- name: meraki deployment
  hosts: localhost
  debugger: on_failed
  vars:
    auth_key: 5e1d8be50f14d4d72eae15fb89da73fb74fe591c
    org_name: FRN Demo
    device_name1: pfs-b_mx1
    device_name2: pfs-b_sw1
    device_name3: pfs-b_ap1
    device_name4: pfs-b_ap2
    serial1: Q2JY-F2KP-JWLM
    serial2: Q2BX-BMSG-74QE
    serial3: Q3AJ-9S8K-WN5R
    serial4: Q2YD-WQSU-M5LK
    network_name: PFS-B
    template_name: PFS-Template-S
    user_vlan_id: 3001
    wireless_vlan_id: 3000
    mgmt_vlan_id: 108
    user_subnet: 10.20.10
    wireless_subnet: 10.20.0
    mgmt_subnet: 10.10.108
    mgmt_mask: 24
    wireless_mask: 24
    user_mask: 24

  tasks:

      - name: csv-read
        read_csv:
          path: devices.csv
          delimiter: ','
        register: devices

      - name: Create site network
        meraki_network:
           auth_key: "{{ auth_key }}"
           state: present
           org_name: "{{ org_name }}"
           name: "{{ network_name }}"
           type:
              - switch
              - appliance
              - wireless
        register: off_network

      - name: Add dev1 to Network
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ serial1 }}"
        register: off_add_dev1

      - debug:
          msg: "{{ off_add_dev1 }}"

      - name: Add dev2 to Network
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ serial2 }}"
        register: off_add_dev2

      - name: Add dev3 to Network
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ serial3 }}"
        register: off_add_dev3

      - name: Add dev4
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ serial4 }}"
        register: off_add_dev4


      - name: Update Dev1 Information
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ serial1 }}"
           name: " {{ device_name1 }}"
           move_map_marker: no
        register: off_update_dev1


      - name: Update Dev2 Information
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ serial2 }}"
           name: " {{ device_name2 }}"
           move_map_marker: no
        register: off_update_dev2


      - name: Update Dev3 Information
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ serial3 }}"
           name: " {{ device_name3 }}"
           move_map_marker: no
        register: off_update_dev3


      - name: Update Dev4 Information
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ serial4 }}"
           name: " {{ device_name4 }}"
           move_map_marker: no
        register: off_update_dev4

      - name: Enable VLAN settings
        uri:
          url: "https://n176.meraki.com/api/v0/networks/{{ off_network.data.id }}/vlansEnabledState"
          method: PUT
          body: '{"enabled":true}'
          validate_certs: no
          headers:
            X-Cisco-Meraki-API-Key: "{{ auth_key }}"
            Content-Type: application/json
        register: response

      - debug:
          msg: "{{ response }}"

      - name: MX Configuration Prompt
        pause:
          prompt: "ENABLE VLANS ON THE MXs THEN PRESS ENTER TO CONTINUE"
        register: vlans_enabled




      - name: Create mgmt Subnet
        meraki_vlan:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           name: mgmt
           vlan_id: "{{ mgmt_vlan_id}}"
           subnet: "{{ mgmt_subnet }}.0/{{mgmt_mask}}"
           appliance_ip: "{{ mgmt_subnet }}.254"


      - name: Create Wireless Subnet
        meraki_vlan:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           name: Wireless
           vlan_id: "{{ wireless_vlan_id}}"
           subnet: "{{ wireless_subnet }}.0/{{wireless_mask}}"
           appliance_ip: "{{ wireless_subnet }}.254"

      - name: Create User Subnet
        meraki_vlan:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           name: Wireless
           vlan_id: "{{ user_vlan_id}}"
           subnet: "{{ user_subnet }}.0/{{user_mask}}"
           appliance_ip: "{{ user_subnet }}.254"
