---
 device-1:
    network_name: PFS-B
    template_name: PFS-Template-S
    device_name: pfs-b_mx1
    device_type: MX67C-WW
    serial_no: Q2JY-F2KP-JWLM
    mac-address: 98:18:88:c7:ec:5b
    vlan_id: 1
    ip_address: 100.20.80.1
    subnet_mask: 255.255.255.0
    gateway_ip: n/a
    dns_server1: 208.67.222.222
    dns_server2: 208.67.220.220

 device-2:
    network_name: PFS-B
    template_name: PFS-Template-S
    device_name: pfs-b_sw1
    device_type: MS120-8LP
    serial_no: Q2BX-BMSG-74QE
    mac-address: 34:56:fe:cc:89:38
    vlan_id: 1
    ip_address: 100.20.80.11
    subnet_mask: 255.255.255.0
    gateway_ip: 100.20.80.1
    dns_server1: 208.67.222.222
    dns_server2: 208.67.220.220

 device-3:
    network_name: PFS-B
    template_name: PFS-Template-S
    device_name: pfs-b_ap1
    device_type: MR70
    serial_no: Q3AJ-9S8K-WN5R
    mac-address: 98:18:88:bc:96:13
    vlan_id: 1
    ip_address: 100.20.80.21
    subnet_mask: 255.255.255.0
    gateway_ip: 100.20.80.1
    dns_server1: 208.67.222.222
    dns_server2: 208.67.220.220

 device-4:
    network_name: PFS-B
    template_name: PFS-Template-S
    device_name: pfs-b_ap2
    device_type: MR70
    serial_no: Q2YD-WQSU-M5LK
    mac-address: e0:cb:bc:b9:f7:24
    vlan_id: 1
    ip_address: 100.20.80.22
    subnet_mask: 255.255.255.0
    gateway_ip: 100.20.80.1
    dns_server1: 208.67.222.222
    dns_server2: 208.67.220.220
