---
- name: meraki deployment
  hosts: localhost
  debugger: on_failed
  vars:
    auth_key: 5e1d8be50f14d4d72eae15fb89da73fb74fe591c
    org_name: FRN Demo

  tasks:

      - name: csv-read
        read_csv:
          path: "{{ path-device }}"
          delimiter: ','
        register: devices

      - name: csv-read
        read_csv:
          path: "{{ path-addressing }}"
          delimiter: ','
        register: addressing

      - name: Create site network
        meraki_network:
           auth_key: "{{ auth_key }}"
           state: present
           org_name: "{{ org_name }}"
           name: "{{ devices.list.0.network_name }}"
           type:
              - switch
              - appliance
              - wireless
        register: off_network

      - name: Add dev1 to Network
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ devices.list.0.serial_no }}"
        register: off_add_dev1

      - name: Add dev2 to Network
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ devices.list.1.serial_no }}"
        register: off_add_dev2

      - name: Add dev3 to Network
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ devices.list.2.serial_no }}"
        register: off_add_dev3

      - name: Add dev4
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ devices.list.3.serial_no }}"
        register: off_add_dev4

      - name: Update Dev1 Information
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ devices.list.0.serial_no }}"
           name: " {{ devices.list.0.device_name }}"
           move_map_marker: no
        register: off_update_dev1


      - name: Update Dev2 Information
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ devices.list.1.serial_no  }}"
           name: " {{ devices.list.1.device_name }}"
           move_map_marker: no
        register: off_update_dev2


      - name: Update Dev3 Information
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ devices.list.2.serial_no  }}"
           name: " {{ devices.list.2.device_name }}"
           move_map_marker: no
        register: off_update_dev3


      - name: Update Dev4 Information
        meraki_device:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           serial: "{{ devices.list.3.serial_no  }}"
           name: " {{ devices.list.3.device_name }}"
           move_map_marker: no
        register: off_update_dev4

      - name: Bind a template from a network
        meraki_config_template:
          auth_key: "{{ auth_key }}"
          state: present
          org_name: "{{ org_name }}"
          net_name: "{{ devices.list.0.network_name }}"
          config_template: "{{ devices.list.0.template_name }}"
        delegate_to: localhost


      - name: Edit first Subnet
        meraki_vlan:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           name: "{{ addressing.list.0.name }}"
           vlan_id: "{{ addressing.list.0.vlan_id }}"
           subnet: "{{ addressing.list.0.network_address }}"
           appliance_ip: "{{ addressing.list.0.default_gw }}"


      - name: Edit second Subnet
        meraki_vlan:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           name: "{{ addressing.list.1.name }}"
           vlan_id: "{{ addressing.list.1.vlan_id }}"
           subnet: "{{ addressing.list.1.network_address }}"
           appliance_ip: "{{ addressing.list.1.default_gw }}"


      - name: Edit third Subnet
        meraki_vlan:
           auth_key: "{{ auth_key }}"
           org_name: "{{ org_name }}"
           net_id: "{{ off_network.data.id }}"
           state: present
           name: "{{ addressing.list.2.name }}"
           vlan_id: "{{ addressing.list.2.vlan_id }}"
           subnet: "{{ addressing.list.2.network_address }}"
           appliance_ip: "{{ addressing.list.2.default_gw }}"


      - name: Edit foruth Subnet
        meraki_vlan:
          auth_key: "{{ auth_key }}"
          org_name: "{{ org_name }}"
          net_id: "{{ off_network.data.id }}"
          state: present
          name: "{{ addressing.list.3.name }}"
          vlan_id: "{{ addressing.list.3.vlan_id }}"
          subnet: "{{ addressing.list.3.network_address }}"
          appliance_ip: "{{ addressing.list.3.default_gw }}"


      - name: Edit fifth Subnet
        meraki_vlan:
          auth_key: "{{ auth_key }}"
          org_name: "{{ org_name }}"
          net_id: "{{ off_network.data.id }}"
          state: present
          name: "{{ addressing.list.4.name }}"
          vlan_id: "{{ addressing.list.4.vlan_id }}"
          subnet: "{{ addressing.list.4.network_address }}"
          appliance_ip: "{{ addressing.list.4.default_gw }}"


      - name: Edit sixth Subnet
        meraki_vlan:
          auth_key: "{{ auth_key }}"
          org_name: "{{ org_name }}"
          net_id: "{{ off_network.data.id }}"
          state: present
          name: "{{ addressing.list.5.name }}"
          vlan_id: "{{ addressing.list.5.vlan_id }}"
          subnet: "{{ addressing.list.5.network_address }}"
          appliance_ip: "{{ addressing.list.5.default_gw }}"


      - name: Edit seventh Subnet
        meraki_vlan:
          auth_key: "{{ auth_key }}"
          org_name: "{{ org_name }}"
          net_id: "{{ off_network.data.id }}"
          state: present
          name: "{{ addressing.list.6.name }}"
          vlan_id: "{{ addressing.list.6.vlan_id }}"
          subnet: "{{ addressing.list.6.network_address }}"
          appliance_ip: "{{ addressing.list.6.default_gw }}"
